In [1]:
import numpy as np

In [11]:
escalar = 5.679
vector = np.array([1,2,3])
matriz = np.array([[1,2],[3,4],[5,6]])
tensor = np.array([
                  [[1,2,3],[4,5,6],[7,8,9]],
                  [[11,12,13],[14,15,16],[17,18,19]],
                  [[21,22,23],[24,25,26],[27,28,29]],
])

In [3]:
matriz_t = matriz.T # transpuesta 
print(matriz_t)

[[1 3 5]
 [2 4 6]]


In [5]:
print(matriz_t.shape)

(2, 3)


In [6]:
print(matriz.shape)

(3, 2)


In [7]:
tensor_t = tensor.T
print(tensor_t)

[[[ 1 11 21]
  [ 4 14 24]
  [ 7 17 27]]

 [[ 2 12 22]
  [ 5 15 25]
  [ 8 18 28]]

 [[ 3 13 23]
  [ 6 16 26]
  [ 9 19 29]]]


In [8]:
print(tensor)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[11 12 13]
  [14 15 16]
  [17 18 19]]

 [[21 22 23]
  [24 25 26]
  [27 28 29]]]


In [9]:
A = np.array([[1,2],[3,4],[5,6]])
B = np.array([[7,8],[9,10],[11,12]])
C = A+B
print(A)
print(B)
print(C)

[[1 2]
 [3 4]
 [5 6]]
[[ 7  8]
 [ 9 10]
 [11 12]]
[[ 8 10]
 [12 14]
 [16 18]]


In [12]:
D = matriz + escalar
print(D)

[[ 6.679  7.679]
 [ 8.679  9.679]
 [10.679 11.679]]


In [17]:
# reto
a = np.array([[1,2,3,4,5],[6,7,8,9,10],[1,2,3,4,5],[6,7,8,9,10],[1,2,3,4,5]])
b = a.T
c = a + b

In [20]:
print(a)
print(b)
print(c)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [ 1  2  3  4  5]]
[[ 1  6  1  6  1]
 [ 2  7  2  7  2]
 [ 3  8  3  8  3]
 [ 4  9  4  9  4]
 [ 5 10  5 10  5]]
[[ 2  8  4 10  6]
 [ 8 14 10 16 12]
 [ 4 10  6 12  8]
 [10 16 12 18 14]
 [ 6 12  8 14 10]]
